language: ruby
rvm:
- 2.6
cache: bundler
before_install:
- gem install bundler
bundler_args: "--without development --jobs=3"
services:
- postgresql
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- cp config/database.yml.travis config/database.yml
script:
- bin/rails db:migrate RAILS_ENV=test
- bin/rails test
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: SGdXmYsYvy5pD86/dHI5fajr6ZM5pMb1aQROtOZMdE7mIr4I/2ymVgd+N+7zplLsEKRicPsIS38tEln9TMBlvGxyJsXc97OBh2RqPP8Vgyh8SG5xQQJbggfJ1B/CGwooC2Ro9xDnXgmnIv70W6w29Pk5fnq/dGGO7AWm6LGovBOmIfZ7ofKW/mgdgd+lWYbzgXwkXL8KV7S6BAbAVAWycGfDc4nPynpEzLUXDfpVVhdab8S0bS/znlljzOGO24dVdefkb3S2mhsqQVJjgRLsOjIswTuao3/iu5Tj8d9xqp3sNDQCatwarpJfYxKMHpwMEK2Pe2z1Ugw6ZTah3ihfnb1U97stJywbUHUKFZ8hWPujOhh7D4rH3xt9Wghf4Yduhp6bwrBlbaoNMQZG7b5mfcmyBWfUe+b2BbXSAxXDaUUHvUGyC8KJCJYEPzcaKI+Fg6IwEt/4/xw5C9UJNiUkCL9+PYARicMfTDVNK4kgakEs7ZWVh603aR8dIIPEOMZ1I3D0iJElfRsu9niGjzfqZuNbrSpetfbVDxZ9+U/8VmyV7Ynhtvqo+jk8SUuqBi/tOBN+ZvvN1hsd5sAf5F1wY0tQTEK273euwsvfUKhbcu4Rx2L0K8BVk+Y/I/GOjbBRkxgZdD8LF6gxTZ87W78RgGBt7YW8b1WEKyc9T+v/IN4=
  on:
    repo: cat2koban/toy_app
  app:
    secure: TBXZnKKDAZGVMmjIDZzn57QsFWjSqUvudmoafEuXPOPWWESxM8PfxWP7ELXp1G8d/rRKrUl0ESFb0O9MNo0+40tD/V8Nq8AlqptVTaqrHH4i61RjpHL6QU7POvGKq+E5Iutc4ZtC6vTe3ejK3f9n1ZB5n0D6KhgX+27Gh8+Cx+mFEhVI9iOxv0k2Y1dF1ybLeq0iYABsrENZhN1mUKj2WCS8Ay5T9x5kI+lYtLx3xJKU3GYrcH1TpXo7kFD9LdoLEsTMAyjd3ysWSh3DFeCp8bWppu20JIxEBuDnrS6UfNdmTpBrjGASy15hl8fL7azC08QU4x3HUxm/ibyCEXbP3rYnjKT+KPLbnErn4FEvyPzDl88sz8PMzsvuSieWYSvXXcgisk0DrbcIa/BbVkzu2YEb2ngLVDZwwVKPs2ho7nVOwUNChPuHV2NYqxeducdcMnULlPooP2/2iPmhpsm47wNb0Y4WUQfJUlutNR60m3fyCe4NEWuHYRs9/nQgABkEBo06GhS9D4a1WPZMLTGKKbmzFspe5pqxPW40hJWYORgb6WBfIGlAz9xsLkFRdP1eGGczY7yMlvwbPM6A5/du0HaDKoTTOIuCwD7xSLcxA4JHO2U2QeU4hkIJkETeFGXpZJbLoH3CnCl1nJkfTNEA5kieGLXS8lEVSVQPsYJ6WXs=
